name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - ".github/workflows/iac.yml"
      - "CarSnapScore/CarSnapScore.CloudInfrastructure/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

permissions:
  id-token: write
  contents: read

env:
  Location: "centralus"

jobs:
  cleanup-resources:
    runs-on: ubuntu-latest
    environment: CleanupResources
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Empty Out Azure Environment
      uses: azure/CLI@v1
      continue-on-error: true
      with:
        azcliversion: 2.48.1
        inlineScript: az group delete --name ${{ vars.RESOURCE_NAME }} --yes
  
  provision-resources:
    runs-on: ubuntu-latest
    environment: 
      name: IaCDeloy
      url: https://${{ steps.swahostname.outputs.DEFAULT_HOSTNAME }}
    needs: cleanup-resources
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: ${{ env.Location }}
        template: ./CarSnapScore/CarSnapScore.CloudInfrastrucure/main.bicep
        parameters: location=${{ env.Location }} commonResourceName=${{ vars.RESOURCE_NAME }}
        failOnStdErr: false
        deploymentName: bicep-ci-${{ github.run_id }}

    - name: Get SWA Default Hostname
      id: swahostname
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: echo DEFAULT_HOSTNAME=$(az staticwebapp show -n ${{ vars.RESOURCE_NAME }}web --query 'defaultHostname') | tr -d '"' >> "$GITHUB_OUTPUT" 

  build-and-deploy-apps:
    runs-on: ubuntu-latest
    environment: AppDeploy
    needs: provision-resources
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy Function App
      uses: ./.github/workflows/function
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}

    - name: Build and Deploy Minimal API
      uses: ./.github/workflows/minimalapi
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}

    - name: Build and Deploy MVC App
      uses: ./.github/workflows/mvc
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}

    - name: Build and Deploy Static Web App
      uses: ./.github/workflows/swa
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}

    - name: Build and Deploy Web API App
      uses: ./.github/workflows/webapi
      with:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        RESOURCE_NAME: ${{ vars.RESOURCE_NAME }}
